### ISSUE TITLE
TextArea1 might work better as a list

### ISSUE THREAD

**Issue by danielvest128** [danxzylo/JavaIISearchEngine#4]
After adding the code to select a file and add it to the list in TextArea1 of searchengineui.AddRemoveFiles I realized it might be easier to work with (especially for removing files) if it were a list instead.

**Comment by danxzylo** [comment]
I like this idea. To clarify, we are talking about a dropdown list?

**Comment by danxzylo** [comment]
On top of this, should we change the text area on the main GUI to a jList as well? Truthfully when designing the GUI, I didn't see the jList and now I feel it's better suited to the project.

**Comment by danielvest128** [comment]
Yes, drop down would work. I was working on the remove file method and was
building a list from the textarea when I thought why not just start with
one?
